# Generated by Django 3.0.7 on 2020-06-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200611_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catrgory',
            new_name='Category',
        ),
    ]
