# Generated by Django 3.0.7 on 2020-06-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200617_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_snippet',
            field=models.CharField(default='Click on the link above to read more.', max_length=255),
        ),
    ]
