# Generated by Django 3.0.7 on 2020-09-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200914_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website_url',
        ),
    ]
